baseurl: "/blog"

# Set layout pages.
defaults:
  - scope:
      path: ""
    values:
      layout: "main"

# Set a custom excerpt separator to override what is rendered for each post on the index page.
excerpt_separator: <!-- excerpt-end -->

# Files to exclude from site conversion.
exclude: [
  "sh-serve.command", 
  "sh-clean.command"
]

# SASS Config
sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag